spring:
  datasource:
    url: jdbc:h2:file:C:/Users/ASUS/Desktop/JBU/구름톤/db/todoapp
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug