spring:
  datasource:
    url: jdbc:h2:file:~/newdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace           # 추가!
    org.hibernate.tool.hbm2ddl: debug   # 추가!

kakao:
  client-id: 52c4872fc30d423c710bb20bb07f874e
  redirect-uri: http://localhost:3000/callback

server:
  address: 0.0.0.0
  port: 8080

#s